name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 764678966792.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker images
        run: |
          docker build -t 764678966792.dkr.ecr.us-east-1.amazonaws.com/devops-task-ui:latest ./ui
          docker build -t 764678966792.dkr.ecr.us-east-1.amazonaws.com/devops-task-api:latest ./api
          docker push 764678966792.dkr.ecr.us-east-1.amazonaws.com/devops-task-ui:latest
          docker push 764678966792.dkr.ecr.us-east-1.amazonaws.com/devops-task-api:latest

      - name: Decode EC2 SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > key.pem
          chmod 600 key.pem

      - name: Deploy on EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull 764678966792.dkr.ecr.us-east-1.amazonaws.com/devops-task-ui:latest
            docker pull 764678966792.dkr.ecr.us-east-1.amazonaws.com/devops-task-api:latest
            cd /home/ec2-user/app || mkdir -p /home/ec2-user/app && cd /home/ec2-user/app
            docker compose down
            docker compose up -d
          EOF
